language: python
install:
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install sphinx"
    - "pip install matplotlib"
    - "python setup.py develop"

script: ./.travis-test-2.18.sh

branches:
    only:
        - master
