# make edits to this line to trigger a new travis build.
# (sometimes it errors out trying to download from PyPI)
language: python
python:
    - "2.7"

notifications:
    email:
        recipients:
            - ryankdale@gmail.com
            - dalerr@niddk.nih.gov
        on_success: always
        on_failure: always

# See http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser)
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"


# Most of this is from http://conda.pydata.org/docs/travis.html
install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda

      # Useful for debugging any issues with conda
    - conda info -a

    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION matplotlib pandas sphinx cython pyyaml numpydoc pyyaml
    - source activate test-environment
    - python setup.py develop

script: ./.travis-test.sh

branches:
    only:
        - master
